const Types = {
  READ_YEARS_REQUEST: '@filter/READ_YEARS_REQUEST',
  READ_YEARS_SUCCESS: '@filter/READ_YEARS_SUCCESS',

  READ_UF_REQUEST: '@filter/READ_UF_REQUEST',
  READ_UF_SUCCESS: '@filter/READ_UF_SUCCESS',

  READ_CITY_REQUEST: '@filter/READ_CITY_REQUEST',
  READ_CITY_SUCCESS: '@filter/READ_CITY_SUCCESS',

  CHANGER_VALUE_FILTER_SELECT: '@filter/CHANGER_VALUE_FILTER_SELECT',
}

export default Types
